service: tsoa-serverless-example

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: npm

functions:
  router:
    handler: src/router.handler
    events:
      - http:
          path: "{proxy+}"
          method: any
